// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface ColumnOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.Column)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Include other fields as necessary
   * </pre>
   *
   * <code>.org.example.ColumnType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Include other fields as necessary
   * </pre>
   *
   * <code>.org.example.ColumnType type = 2;</code>
   * @return The type.
   */
  org.example.ColumnType getType();
}
