// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

/**
 * <pre>
 * Enum for ColumnType
 * </pre>
 *
 * Protobuf enum {@code org.example.ColumnType}
 */
public enum ColumnType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>INT = 0;</code>
   */
  INT(0),
  /**
   * <code>CHAR = 1;</code>
   */
  CHAR(1),
  /**
   * <code>REAL = 2;</code>
   */
  REAL(2),
  /**
   * <code>STRING = 3;</code>
   */
  STRING(3),
  /**
   * <code>CHARINVL = 4;</code>
   */
  CHARINVL(4),
  /**
   * <code>STRINGINVL = 5;</code>
   */
  STRINGINVL(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INT = 0;</code>
   */
  public static final int INT_VALUE = 0;
  /**
   * <code>CHAR = 1;</code>
   */
  public static final int CHAR_VALUE = 1;
  /**
   * <code>REAL = 2;</code>
   */
  public static final int REAL_VALUE = 2;
  /**
   * <code>STRING = 3;</code>
   */
  public static final int STRING_VALUE = 3;
  /**
   * <code>CHARINVL = 4;</code>
   */
  public static final int CHARINVL_VALUE = 4;
  /**
   * <code>STRINGINVL = 5;</code>
   */
  public static final int STRINGINVL_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ColumnType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ColumnType forNumber(int value) {
    switch (value) {
      case 0: return INT;
      case 1: return CHAR;
      case 2: return REAL;
      case 3: return STRING;
      case 4: return CHARINVL;
      case 5: return STRINGINVL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ColumnType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ColumnType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ColumnType>() {
          public ColumnType findValueByNumber(int number) {
            return ColumnType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.example.RemoteDBProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ColumnType[] VALUES = values();

  public static ColumnType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ColumnType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:org.example.ColumnType)
}

