// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface CreateTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.CreateTableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
