// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface CreateTestTableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.CreateTestTableRequest)
    com.google.protobuf.MessageOrBuilder {
}
