// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface DeleteColumnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.DeleteColumnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tableIndex = 1;</code>
   * @return The tableIndex.
   */
  int getTableIndex();

  /**
   * <code>int32 columnIndex = 2;</code>
   * @return The columnIndex.
   */
  int getColumnIndex();
}
