// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface DeleteRowRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.DeleteRowRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tableIndex = 1;</code>
   * @return The tableIndex.
   */
  int getTableIndex();

  /**
   * <code>int32 rowIndex = 2;</code>
   * @return The rowIndex.
   */
  int getRowIndex();
}
