// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface EditCellRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.EditCellRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tableIndex = 1;</code>
   * @return The tableIndex.
   */
  int getTableIndex();

  /**
   * <code>int32 rowIndex = 2;</code>
   * @return The rowIndex.
   */
  int getRowIndex();

  /**
   * <code>int32 columnIndex = 3;</code>
   * @return The columnIndex.
   */
  int getColumnIndex();

  /**
   * <code>string value = 4;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 4;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
