// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface GetColumnsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.GetColumnsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.Column columns = 1;</code>
   */
  java.util.List<org.example.Column> 
      getColumnsList();
  /**
   * <code>repeated .org.example.Column columns = 1;</code>
   */
  org.example.Column getColumns(int index);
  /**
   * <code>repeated .org.example.Column columns = 1;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated .org.example.Column columns = 1;</code>
   */
  java.util.List<? extends org.example.ColumnOrBuilder> 
      getColumnsOrBuilderList();
  /**
   * <code>repeated .org.example.Column columns = 1;</code>
   */
  org.example.ColumnOrBuilder getColumnsOrBuilder(
      int index);
}
