// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface GetRowsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.GetRowsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.Row rows = 1;</code>
   */
  java.util.List<org.example.Row> 
      getRowsList();
  /**
   * <code>repeated .org.example.Row rows = 1;</code>
   */
  org.example.Row getRows(int index);
  /**
   * <code>repeated .org.example.Row rows = 1;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .org.example.Row rows = 1;</code>
   */
  java.util.List<? extends org.example.RowOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .org.example.Row rows = 1;</code>
   */
  org.example.RowOrBuilder getRowsOrBuilder(
      int index);
}
