// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface GetRowsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.GetRowsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tableIndex = 1;</code>
   * @return The tableIndex.
   */
  int getTableIndex();
}
