// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface GetTablesDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.GetTablesDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.example.TableData tablesData = 1;</code>
   */
  java.util.List<org.example.TableData> 
      getTablesDataList();
  /**
   * <code>repeated .org.example.TableData tablesData = 1;</code>
   */
  org.example.TableData getTablesData(int index);
  /**
   * <code>repeated .org.example.TableData tablesData = 1;</code>
   */
  int getTablesDataCount();
  /**
   * <code>repeated .org.example.TableData tablesData = 1;</code>
   */
  java.util.List<? extends org.example.TableDataOrBuilder> 
      getTablesDataOrBuilderList();
  /**
   * <code>repeated .org.example.TableData tablesData = 1;</code>
   */
  org.example.TableDataOrBuilder getTablesDataOrBuilder(
      int index);
}
