// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface GetTablesDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.GetTablesDataRequest)
    com.google.protobuf.MessageOrBuilder {
}
