// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface MergeTablesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.MergeTablesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Name1 = 1;</code>
   * @return The name1.
   */
  java.lang.String getName1();
  /**
   * <code>string Name1 = 1;</code>
   * @return The bytes for name1.
   */
  com.google.protobuf.ByteString
      getName1Bytes();

  /**
   * <code>string Name2 = 2;</code>
   * @return The name2.
   */
  java.lang.String getName2();
  /**
   * <code>string Name2 = 2;</code>
   * @return The bytes for name2.
   */
  com.google.protobuf.ByteString
      getName2Bytes();
}
