// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public final class RemoteDBProto {
  private RemoteDBProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_GetRowsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_GetRowsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_GetRowsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_GetRowsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_GetColumnsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_GetColumnsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_GetColumnsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_GetColumnsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_GetTablesDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_GetTablesDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_GetTablesDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_GetTablesDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_CreateTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_CreateTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_CreateTableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_CreateTableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AddRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AddRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AddRowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AddRowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AddColumnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AddColumnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_AddColumnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_AddColumnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Row_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_Row_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Column_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_Column_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_TableData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_TableData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_DeleteTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_DeleteTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_DeleteTableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_DeleteTableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_DeleteColumnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_DeleteColumnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_DeleteColumnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_DeleteColumnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_DeleteRowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_DeleteRowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_DeleteRowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_DeleteRowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_EditCellRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_EditCellRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_EditCellResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_EditCellResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_CreateTestTableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_CreateTestTableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_CreateTestTableResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_CreateTestTableResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_MergeTablesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_MergeTablesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_MergeTablesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_MergeTablesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016generate.proto\022\013org.example\"$\n\016GetRows" +
      "Request\022\022\n\ntableIndex\030\001 \001(\005\"1\n\017GetRowsRe" +
      "sponse\022\036\n\004rows\030\001 \003(\0132\020.org.example.Row\"\'" +
      "\n\021GetColumnsRequest\022\022\n\ntableIndex\030\001 \001(\005\"" +
      ":\n\022GetColumnsResponse\022$\n\007columns\030\001 \003(\0132\023" +
      ".org.example.Column\"\026\n\024GetTablesDataRequ" +
      "est\"C\n\025GetTablesDataResponse\022*\n\ntablesDa" +
      "ta\030\001 \003(\0132\026.org.example.TableData\"\"\n\022Crea" +
      "teTableRequest\022\014\n\004name\030\001 \001(\t\"&\n\023CreateTa" +
      "bleResponse\022\017\n\007success\030\001 \001(\010\"#\n\rAddRowRe" +
      "quest\022\022\n\ntableIndex\030\001 \001(\005\"!\n\016AddRowRespo" +
      "nse\022\017\n\007success\030\001 \001(\010\"a\n\020AddColumnRequest" +
      "\022\022\n\ntableIndex\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022+\n\nco" +
      "lumnType\030\003 \001(\0162\027.org.example.ColumnType\"" +
      "$\n\021AddColumnResponse\022\017\n\007success\030\001 \001(\010\"\025\n" +
      "\003Row\022\016\n\006values\030\001 \003(\t\"=\n\006Column\022\014\n\004name\030\001" +
      " \001(\t\022%\n\004type\030\002 \001(\0162\027.org.example.ColumnT" +
      "ype\"(\n\tTableData\022\014\n\004name\030\001 \001(\t\022\r\n\005index\030" +
      "\002 \001(\005\"(\n\022DeleteTableRequest\022\022\n\ntableInde" +
      "x\030\001 \001(\005\"&\n\023DeleteTableResponse\022\017\n\007succes" +
      "s\030\001 \001(\010\">\n\023DeleteColumnRequest\022\022\n\ntableI" +
      "ndex\030\001 \001(\005\022\023\n\013columnIndex\030\002 \001(\005\"\'\n\024Delet" +
      "eColumnResponse\022\017\n\007success\030\001 \001(\010\"8\n\020Dele" +
      "teRowRequest\022\022\n\ntableIndex\030\001 \001(\005\022\020\n\010rowI" +
      "ndex\030\002 \001(\005\"$\n\021DeleteRowResponse\022\017\n\007succe" +
      "ss\030\001 \001(\010\"[\n\017EditCellRequest\022\022\n\ntableInde" +
      "x\030\001 \001(\005\022\020\n\010rowIndex\030\002 \001(\005\022\023\n\013columnIndex" +
      "\030\003 \001(\005\022\r\n\005value\030\004 \001(\t\"#\n\020EditCellRespons" +
      "e\022\017\n\007success\030\001 \001(\010\"\030\n\026CreateTestTableReq" +
      "uest\"*\n\027CreateTestTableResponse\022\017\n\007succe" +
      "ss\030\001 \001(\010\"2\n\022MergeTablesRequest\022\r\n\005Name1\030" +
      "\001 \001(\t\022\r\n\005Name2\030\002 \001(\t\"&\n\023MergeTablesRespo" +
      "nse\022\017\n\007success\030\001 \001(\010*S\n\nColumnType\022\007\n\003IN" +
      "T\020\000\022\010\n\004CHAR\020\001\022\010\n\004REAL\020\002\022\n\n\006STRING\020\003\022\014\n\010C" +
      "HARINVL\020\004\022\016\n\nSTRINGINVL\020\0052\304\007\n\010RemoteDB\022D" +
      "\n\007GetRows\022\033.org.example.GetRowsRequest\032\034" +
      ".org.example.GetRowsResponse\022M\n\nGetColum" +
      "ns\022\036.org.example.GetColumnsRequest\032\037.org" +
      ".example.GetColumnsResponse\022V\n\rGetTables" +
      "Data\022!.org.example.GetTablesDataRequest\032" +
      "\".org.example.GetTablesDataResponse\022P\n\013C" +
      "reateTable\022\037.org.example.CreateTableRequ" +
      "est\032 .org.example.CreateTableResponse\022A\n" +
      "\006AddRow\022\032.org.example.AddRowRequest\032\033.or" +
      "g.example.AddRowResponse\022J\n\tAddColumn\022\035." +
      "org.example.AddColumnRequest\032\036.org.examp" +
      "le.AddColumnResponse\022P\n\013DeleteTable\022\037.or" +
      "g.example.DeleteTableRequest\032 .org.examp" +
      "le.DeleteTableResponse\022S\n\014DeleteColumn\022 " +
      ".org.example.DeleteColumnRequest\032!.org.e" +
      "xample.DeleteColumnResponse\022J\n\tDeleteRow" +
      "\022\035.org.example.DeleteRowRequest\032\036.org.ex" +
      "ample.DeleteRowResponse\022G\n\010EditCell\022\034.or" +
      "g.example.EditCellRequest\032\035.org.example." +
      "EditCellResponse\022\\\n\017CreateTestTable\022#.or" +
      "g.example.CreateTestTableRequest\032$.org.e" +
      "xample.CreateTestTableResponse\022P\n\013MergeT" +
      "ables\022\037.org.example.MergeTablesRequest\032 " +
      ".org.example.MergeTablesResponseB$\n\013org." +
      "exampleB\rRemoteDBProtoP\001\242\002\003RDBb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_GetRowsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_GetRowsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_GetRowsRequest_descriptor,
        new java.lang.String[] { "TableIndex", });
    internal_static_org_example_GetRowsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_GetRowsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_GetRowsResponse_descriptor,
        new java.lang.String[] { "Rows", });
    internal_static_org_example_GetColumnsRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_example_GetColumnsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_GetColumnsRequest_descriptor,
        new java.lang.String[] { "TableIndex", });
    internal_static_org_example_GetColumnsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_example_GetColumnsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_GetColumnsResponse_descriptor,
        new java.lang.String[] { "Columns", });
    internal_static_org_example_GetTablesDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_example_GetTablesDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_GetTablesDataRequest_descriptor,
        new java.lang.String[] { });
    internal_static_org_example_GetTablesDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_example_GetTablesDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_GetTablesDataResponse_descriptor,
        new java.lang.String[] { "TablesData", });
    internal_static_org_example_CreateTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_example_CreateTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_CreateTableRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_org_example_CreateTableResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_example_CreateTableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_CreateTableResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_org_example_AddRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_org_example_AddRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AddRowRequest_descriptor,
        new java.lang.String[] { "TableIndex", });
    internal_static_org_example_AddRowResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_org_example_AddRowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AddRowResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_org_example_AddColumnRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_org_example_AddColumnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AddColumnRequest_descriptor,
        new java.lang.String[] { "TableIndex", "Name", "ColumnType", });
    internal_static_org_example_AddColumnResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_org_example_AddColumnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_AddColumnResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_org_example_Row_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_org_example_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_Row_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_org_example_Column_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_org_example_Column_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_Column_descriptor,
        new java.lang.String[] { "Name", "Type", });
    internal_static_org_example_TableData_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_org_example_TableData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_TableData_descriptor,
        new java.lang.String[] { "Name", "Index", });
    internal_static_org_example_DeleteTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_org_example_DeleteTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_DeleteTableRequest_descriptor,
        new java.lang.String[] { "TableIndex", });
    internal_static_org_example_DeleteTableResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_org_example_DeleteTableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_DeleteTableResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_org_example_DeleteColumnRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_org_example_DeleteColumnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_DeleteColumnRequest_descriptor,
        new java.lang.String[] { "TableIndex", "ColumnIndex", });
    internal_static_org_example_DeleteColumnResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_org_example_DeleteColumnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_DeleteColumnResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_org_example_DeleteRowRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_org_example_DeleteRowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_DeleteRowRequest_descriptor,
        new java.lang.String[] { "TableIndex", "RowIndex", });
    internal_static_org_example_DeleteRowResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_org_example_DeleteRowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_DeleteRowResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_org_example_EditCellRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_org_example_EditCellRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_EditCellRequest_descriptor,
        new java.lang.String[] { "TableIndex", "RowIndex", "ColumnIndex", "Value", });
    internal_static_org_example_EditCellResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_org_example_EditCellResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_EditCellResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_org_example_CreateTestTableRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_org_example_CreateTestTableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_CreateTestTableRequest_descriptor,
        new java.lang.String[] { });
    internal_static_org_example_CreateTestTableResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_org_example_CreateTestTableResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_CreateTestTableResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_org_example_MergeTablesRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_org_example_MergeTablesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_MergeTablesRequest_descriptor,
        new java.lang.String[] { "Name1", "Name2", });
    internal_static_org_example_MergeTablesResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_org_example_MergeTablesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_MergeTablesResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
