// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: generate.proto

package org.example;

public interface RowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.Row)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * As per your Row class
   * </pre>
   *
   * <code>repeated string values = 1;</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.String>
      getValuesList();
  /**
   * <pre>
   * As per your Row class
   * </pre>
   *
   * <code>repeated string values = 1;</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <pre>
   * As per your Row class
   * </pre>
   *
   * <code>repeated string values = 1;</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  java.lang.String getValues(int index);
  /**
   * <pre>
   * As per your Row class
   * </pre>
   *
   * <code>repeated string values = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the values at the given index.
   */
  com.google.protobuf.ByteString
      getValuesBytes(int index);
}
